### ISSUE TITLE
Tracking issue for v0.1 release

### ISSUE THREAD

**Issue by phil-opp** [dora-rs/dora#12]
- [x] dataflow/YAML spec
- [x] Rust API
- [x] Python API
  - [x] Operators: https://github.com/futurewei-tech/dora/pull/30
  - [x] Custom Nodes: #54 
- [x] C API
  - [x] Operators: https://github.com/futurewei-tech/dora-rs/pull/29
  - [x] Custom Nodes: https://github.com/dora-rs/dora/pull/57
- [x] demo use cases
  - [x] Rust: https://github.com/dora-rs/dora/pull/65
  - [x] C: #29 
  - [x] Python: #67 
  - [x] C++: #66 
- [x] Support Windows and macOS as well: https://github.com/dora-rs/dora/pull/73
- [ ] command line for contolling nodes/operators
  - see #81 and #84 
- [ ] zero-copy I/O (see #86 and #87)

Postponed:

- ~C++ API~

**Comment by phil-opp** [comment]
The remaining items are tracked in the [`v0.1` milestone](https://github.com/dora-rs/dora/milestone/1).
