### ISSUE TITLE
Tracking issue for a Pylot MVP on Dora Python API.

### ISSUE THREAD

**Issue by haixuanTao** [dora-rs/dora#21]
Tracking issue for a Pylot MVP on Dora Python API. Pylot is going to validate and benchmark design choices made by DORA.

## CARLA bridge
- [x] Spawn a 'hero' vehicle.
- [x] Spawn other vehicles representing traffic.
- [x] Spawn pedestrians.
- [x] Attach a camera.
- [x] Attach a Depth Camera.
- [x] Attach a segmentation Camera.
- [x] Send position information.

## Detection
- [x] Port DL Obstacle operator.
- [x] Port DL traffic light operator.
- [x] Port perfect obstacle operator.
- [x] Port obstacle location operator.
- [x] Port obstacle trajectory prediction operator.

## Planning
- [x] Port route planning operator.

## Visualisation
- [x] Visualize image from camera.
- [x] Visualize obstacle from camera.
- [x] VIsualize waypoints from camera.

## Control
- [x] Port PID Controller Operator
- [x] Control Operator 

## Deployment
- [x] Package Demo into a Docker

## Bug
- [ ] Upgrade Carla to latest version
- [x] Fix: "Illegal Instruction Error"

Those implementation are currently committed into #18.
